Player 1:
  Start: Start
  Select: Select
  Triangle: Triangle
  Circle: Circle
  Cross: Cross
  Square: Square
  Move: R1
  T: R2
  X-Axis: Left Stick X-Axis
  Y-Axis: Left Stick Y-Axis
  Sharpshooter Firing Mode 1: D-Pad Left
  Sharpshooter Firing Mode 2: D-Pad Up
  Sharpshooter Firing Mode 3: D-Pad Right
  Sharpshooter Trigger: L1
  Sharpshooter Reload: L2
  Racing Wheel D-Pad Up: D-Pad Up
  Racing Wheel D-Pad Right: D-Pad Right
  Racing Wheel D-Pad Down: D-Pad Down
  Racing Wheel D-Pad Left: D-Pad Left
  Racing Wheel Throttle: Right Stick Up
  Racing Wheel L1: L1
  Racing Wheel R1: R1
  Racing Wheel L2: L2
  Racing Wheel R2: R2
  Racing Wheel Paddle L: L3
  Racing Wheel Paddle R: R3
  External Device: Disconnected
Player 2:
  Start: Start
  Select: Select
  Triangle: Triangle
  Circle: Circle
  Cross: Cross
  Square: Square
  Move: R1
  T: R2
  X-Axis: Left Stick X-Axis
  Y-Axis: Left Stick Y-Axis
  Sharpshooter Firing Mode 1: D-Pad Left
  Sharpshooter Firing Mode 2: D-Pad Up
  Sharpshooter Firing Mode 3: D-Pad Right
  Sharpshooter Trigger: L1
  Sharpshooter Reload: L2
  Racing Wheel D-Pad Up: D-Pad Up
  Racing Wheel D-Pad Right: D-Pad Right
  Racing Wheel D-Pad Down: D-Pad Down
  Racing Wheel D-Pad Left: D-Pad Left
  Racing Wheel Throttle: Right Stick Up
  Racing Wheel L1: L1
  Racing Wheel R1: R1
  Racing Wheel L2: L2
  Racing Wheel R2: R2
  Racing Wheel Paddle L: L3
  Racing Wheel Paddle R: R3
  External Device: Disconnected
Player 3:
  Start: Start
  Select: Select
  Triangle: Triangle
  Circle: Circle
  Cross: Cross
  Square: Square
  Move: R1
  T: R2
  X-Axis: Left Stick X-Axis
  Y-Axis: Left Stick Y-Axis
  Sharpshooter Firing Mode 1: D-Pad Left
  Sharpshooter Firing Mode 2: D-Pad Up
  Sharpshooter Firing Mode 3: D-Pad Right
  Sharpshooter Trigger: L1
  Sharpshooter Reload: L2
  Racing Wheel D-Pad Up: D-Pad Up
  Racing Wheel D-Pad Right: D-Pad Right
  Racing Wheel D-Pad Down: D-Pad Down
  Racing Wheel D-Pad Left: D-Pad Left
  Racing Wheel Throttle: Right Stick Up
  Racing Wheel L1: L1
  Racing Wheel R1: R1
  Racing Wheel L2: L2
  Racing Wheel R2: R2
  Racing Wheel Paddle L: L3
  Racing Wheel Paddle R: R3
  External Device: Disconnected
Player 4:
  Start: Start
  Select: Select
  Triangle: Triangle
  Circle: Circle
  Cross: Cross
  Square: Square
  Move: R1
  T: R2
  X-Axis: Left Stick X-Axis
  Y-Axis: Left Stick Y-Axis
  Sharpshooter Firing Mode 1: D-Pad Left
  Sharpshooter Firing Mode 2: D-Pad Up
  Sharpshooter Firing Mode 3: D-Pad Right
  Sharpshooter Trigger: L1
  Sharpshooter Reload: L2
  Racing Wheel D-Pad Up: D-Pad Up
  Racing Wheel D-Pad Right: D-Pad Right
  Racing Wheel D-Pad Down: D-Pad Down
  Racing Wheel D-Pad Left: D-Pad Left
  Racing Wheel Throttle: Right Stick Up
  Racing Wheel L1: L1
  Racing Wheel R1: R1
  Racing Wheel L2: L2
  Racing Wheel R2: R2
  Racing Wheel Paddle L: L3
  Racing Wheel Paddle R: R3
  External Device: Disconnected