Player 1:
  Start: Mouse Button 6
  Select: Mouse Button 7
  Triangle: Mouse Button 8
  Circle: Mouse Button 4
  Cross: Mouse Button 5
  Square: Mouse Button 3
  Move: Mouse Button 2
  T: Mouse Button 1
  Combo: ""
  Combo Start: ""
  Combo Select: ""
  Combo Triangle: ""
  Combo Circle: ""
  Combo Cross: ""
  Combo Square: ""
  Combo Move: ""
  Combo T: ""
  Sharpshooter Firing Mode 1: ""
  Sharpshooter Firing Mode 2: ""
  Sharpshooter Firing Mode 3: ""
  Sharpshooter Trigger: ""
  Sharpshooter Reload: ""
  Combo Sharpshooter Firing Mode 1: ""
  Combo Sharpshooter Firing Mode 2: ""
  Combo Sharpshooter Firing Mode 3: ""
  Combo Sharpshooter Trigger: ""
  Combo Sharpshooter Reload: ""
  Racing Wheel D-Pad Up: ""
  Racing Wheel D-Pad Right: ""
  Racing Wheel D-Pad Down: ""
  Racing Wheel D-Pad Left: ""
  Racing Wheel Throttle: ""
  Racing Wheel L1: ""
  Racing Wheel R1: ""
  Racing Wheel L2: ""
  Racing Wheel R2: ""
  Racing Wheel Paddle L: ""
  Racing Wheel Paddle R: ""
  Combo Racing Wheel D-Pad Up: ""
  Combo Racing Wheel D-Pad Right: ""
  Combo Racing Wheel D-Pad Down: ""
  Combo Racing Wheel D-Pad Left: ""
  Combo Racing Wheel Throttle: ""
  Combo Racing Wheel L1: ""
  Combo Racing Wheel R1: ""
  Combo Racing Wheel L2: ""
  Combo Racing Wheel R2: ""
  Combo Racing Wheel Paddle L: ""
  Combo Racing Wheel Paddle R: ""
  External Device: Disconnected
Player 2:
  Start: Mouse Button 6
  Select: Mouse Button 7
  Triangle: Mouse Button 8
  Circle: Mouse Button 4
  Cross: Mouse Button 5
  Square: Mouse Button 3
  Move: Mouse Button 2
  T: Mouse Button 1
  Combo: ""
  Combo Start: ""
  Combo Select: ""
  Combo Triangle: ""
  Combo Circle: ""
  Combo Cross: ""
  Combo Square: ""
  Combo Move: ""
  Combo T: ""
  Sharpshooter Firing Mode 1: ""
  Sharpshooter Firing Mode 2: ""
  Sharpshooter Firing Mode 3: ""
  Sharpshooter Trigger: ""
  Sharpshooter Reload: ""
  Combo Sharpshooter Firing Mode 1: ""
  Combo Sharpshooter Firing Mode 2: ""
  Combo Sharpshooter Firing Mode 3: ""
  Combo Sharpshooter Trigger: ""
  Combo Sharpshooter Reload: ""
  Racing Wheel D-Pad Up: ""
  Racing Wheel D-Pad Right: ""
  Racing Wheel D-Pad Down: ""
  Racing Wheel D-Pad Left: ""
  Racing Wheel Throttle: ""
  Racing Wheel L1: ""
  Racing Wheel R1: ""
  Racing Wheel L2: ""
  Racing Wheel R2: ""
  Racing Wheel Paddle L: ""
  Racing Wheel Paddle R: ""
  Combo Racing Wheel D-Pad Up: ""
  Combo Racing Wheel D-Pad Right: ""
  Combo Racing Wheel D-Pad Down: ""
  Combo Racing Wheel D-Pad Left: ""
  Combo Racing Wheel Throttle: ""
  Combo Racing Wheel L1: ""
  Combo Racing Wheel R1: ""
  Combo Racing Wheel L2: ""
  Combo Racing Wheel R2: ""
  Combo Racing Wheel Paddle L: ""
  Combo Racing Wheel Paddle R: ""
  External Device: Disconnected
Player 3:
  Start: Mouse Button 6
  Select: Mouse Button 7
  Triangle: Mouse Button 8
  Circle: Mouse Button 4
  Cross: Mouse Button 5
  Square: Mouse Button 3
  Move: Mouse Button 2
  T: Mouse Button 1
  Combo: ""
  Combo Start: ""
  Combo Select: ""
  Combo Triangle: ""
  Combo Circle: ""
  Combo Cross: ""
  Combo Square: ""
  Combo Move: ""
  Combo T: ""
  Sharpshooter Firing Mode 1: ""
  Sharpshooter Firing Mode 2: ""
  Sharpshooter Firing Mode 3: ""
  Sharpshooter Trigger: ""
  Sharpshooter Reload: ""
  Combo Sharpshooter Firing Mode 1: ""
  Combo Sharpshooter Firing Mode 2: ""
  Combo Sharpshooter Firing Mode 3: ""
  Combo Sharpshooter Trigger: ""
  Combo Sharpshooter Reload: ""
  Racing Wheel D-Pad Up: ""
  Racing Wheel D-Pad Right: ""
  Racing Wheel D-Pad Down: ""
  Racing Wheel D-Pad Left: ""
  Racing Wheel Throttle: ""
  Racing Wheel L1: ""
  Racing Wheel R1: ""
  Racing Wheel L2: ""
  Racing Wheel R2: ""
  Racing Wheel Paddle L: ""
  Racing Wheel Paddle R: ""
  Combo Racing Wheel D-Pad Up: ""
  Combo Racing Wheel D-Pad Right: ""
  Combo Racing Wheel D-Pad Down: ""
  Combo Racing Wheel D-Pad Left: ""
  Combo Racing Wheel Throttle: ""
  Combo Racing Wheel L1: ""
  Combo Racing Wheel R1: ""
  Combo Racing Wheel L2: ""
  Combo Racing Wheel R2: ""
  Combo Racing Wheel Paddle L: ""
  Combo Racing Wheel Paddle R: ""
  External Device: Disconnected
Player 4:
  Start: Mouse Button 6
  Select: Mouse Button 7
  Triangle: Mouse Button 8
  Circle: Mouse Button 4
  Cross: Mouse Button 5
  Square: Mouse Button 3
  Move: Mouse Button 2
  T: Mouse Button 1
  Combo: ""
  Combo Start: ""
  Combo Select: ""
  Combo Triangle: ""
  Combo Circle: ""
  Combo Cross: ""
  Combo Square: ""
  Combo Move: ""
  Combo T: ""
  Sharpshooter Firing Mode 1: ""
  Sharpshooter Firing Mode 2: ""
  Sharpshooter Firing Mode 3: ""
  Sharpshooter Trigger: ""
  Sharpshooter Reload: ""
  Combo Sharpshooter Firing Mode 1: ""
  Combo Sharpshooter Firing Mode 2: ""
  Combo Sharpshooter Firing Mode 3: ""
  Combo Sharpshooter Trigger: ""
  Combo Sharpshooter Reload: ""
  Racing Wheel D-Pad Up: ""
  Racing Wheel D-Pad Right: ""
  Racing Wheel D-Pad Down: ""
  Racing Wheel D-Pad Left: ""
  Racing Wheel Throttle: ""
  Racing Wheel L1: ""
  Racing Wheel R1: ""
  Racing Wheel L2: ""
  Racing Wheel R2: ""
  Racing Wheel Paddle L: ""
  Racing Wheel Paddle R: ""
  Combo Racing Wheel D-Pad Up: ""
  Combo Racing Wheel D-Pad Right: ""
  Combo Racing Wheel D-Pad Down: ""
  Combo Racing Wheel D-Pad Left: ""
  Combo Racing Wheel Throttle: ""
  Combo Racing Wheel L1: ""
  Combo Racing Wheel R1: ""
  Combo Racing Wheel L2: ""
  Combo Racing Wheel R2: ""
  Combo Racing Wheel Paddle L: ""
  Combo Racing Wheel Paddle R: ""
  External Device: Disconnected